name: Question
description: Ask a question about the demo or roadmap.
title: "Question: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
